spring.application.name=techlab-web
server.port=8081
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
spring.messages.basename=messages
spring.messages.encoding=UTF-8